language: python
python:
  - "2.7"
env:
  - DJANGO=1.3
  - DJANGO=1.4
  - DJANGO=1.5
install:
  - pip install -q Django==$DJANGO --use-mirrors
  - pip install -r requirements.txt --use-mirrors
  - pip install flake8 --use-mirrors
  - pip install -q -e . --use-mirrors
before_script:
  - "flake8 push_notifications"
script:
  - python tests/runtests.py
